blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Join the Eating Animation Modded Discord
    url: https://discord.gg/TcmUQHZ5U4
    about: Get support, share feedback, or chat with the community.
